from videojuegos import Videojuegos

zelda = Videojuegos("Zelda", "Nintendo", "En venta", 30).añadir_videojuego()
mario = Videojuegos("Mario", "Switch", "En venta", 40).añadir_videojuego()
dark_souls = Videojuegos("Dark Souls", "Todas", "Agotado", 0).añadir_videojuego()
metal_gear = Videojuegos("Metal Gear", "PlayStation", "Obsoleto", 0).añadir_videojuego()
fifa = Videojuegos("Fifa24", "Todas", "En venta", 200).añadir_videojuego()
monster_hunter = Videojuegos("Monster Hunter", "Todas", "En venta", 50).añadir_videojuego()
hollow_knight = Videojuegos("Hollow Knight", "Todas", "En venta", 30).añadir_videojuego()
elden_ring = Videojuegos("Elden Ring", "Todas", "En venta", 60).añadir_videojuego()
tekken = Videojuegos("Tekken 8", "Todas", "En venta", 40).añadir_videojuego()
pokemon1 = Videojuegos("Pokemon Oro", "Nintendo", "Obsoleto", 0).añadir_videojuego()
pokemon2 = Videojuegos("Pokemon Púrpura", "Switch", "En venta", 15).añadir_videojuego()
call_duty = Videojuegos("Call of Duty: Modern Warfare 2", "PlayStation", "Obsoleto", 0).añadir_videojuego()
battlefield = Videojuegos("Battlefield V", "Todas", "En venta", 20).añadir_videojuego()
wow = Videojuegos("World Of Warcraft", "PC", "Agotado", 0).añadir_videojuego()
rust  = Videojuegos("Rust", "PC", "En venta", 50).añadir_videojuego()
sekiro = Videojuegos("Sekiro: Shadows Die Twice", "Todas", "Agotado", 0).añadir_videojuego()
smbb = Videojuegos("Super Smash Bros Brawl", "Switch", "En venta", 20).añadir_videojuego()